import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val androidx_appcompat_appcompat: String = "androidx.appcompat:appcompat:" +
            Versions.androidx_appcompat_appcompat

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val cardview: String = "androidx.cardview:cardview:" + Versions.cardview

    /**
     * http://tools.android.com
     */
    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
            Versions.constraintlayout

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val androidx_core_core_ktx: String = "androidx.core:core-ktx:" +
            Versions.androidx_core_core_ktx

    const val databinding_adapters: String = "androidx.databinding:databinding-adapters:" +
            Versions.androidx_databinding

    /**
     * https://developer.android.com/studio
     */
    const val databinding_common: String = "androidx.databinding:databinding-common:" +
            Versions.androidx_databinding

    /**
     * https://developer.android.com/studio
     */
    const val databinding_compiler: String = "androidx.databinding:databinding-compiler:" +
            Versions.androidx_databinding

    const val databinding_runtime: String = "androidx.databinding:databinding-runtime:" +
            Versions.androidx_databinding

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val fragment_ktx: String = "androidx.fragment:fragment-ktx:" + Versions.fragment_ktx

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val legacy_support_v4: String = "androidx.legacy:legacy-support-v4:" +
            Versions.legacy_support_v4

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val lifecycle_extensions: String = "androidx.lifecycle:lifecycle-extensions:" +
            Versions.androidx_lifecycle

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val lifecycle_reactivestreams_ktx: String =
            "androidx.lifecycle:lifecycle-reactivestreams-ktx:" + Versions.androidx_lifecycle

    const val multidex: String = "androidx.multidex:multidex:" + Versions.multidex

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_fragment_ktx: String = "androidx.navigation:navigation-fragment-ktx:" +
            Versions.navigation_fragment_ktx

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_safe_args_gradle_plugin: String =
            "androidx.navigation:navigation-safe-args-gradle-plugin:" +
            Versions.navigation_safe_args_gradle_plugin

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:" +
            Versions.navigation_ui_ktx

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val palette: String = "androidx.palette:palette:" + Versions.palette

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val recyclerview: String = "androidx.recyclerview:recyclerview:" + Versions.recyclerview

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val room_compiler: String = "androidx.room:room-compiler:" + Versions.androidx_room

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val room_runtime: String = "androidx.room:room-runtime:" + Versions.androidx_room

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val room_rxjava2: String = "androidx.room:room-rxjava2:" + Versions.androidx_room

    /**
     * https://developer.android.com/testing
     */
    const val espresso_core: String = "androidx.test.espresso:espresso-core:" +
            Versions.espresso_core

    /**
     * https://developer.android.com/testing
     */
    const val androidx_test_runner: String = "androidx.test:runner:" + Versions.androidx_test_runner

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val vectordrawable_animated: String = "androidx.vectordrawable:vectordrawable-animated:" +
            Versions.vectordrawable_animated

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val work_runtime_ktx: String = "androidx.work:work-runtime-ktx:" + Versions.androidx_work

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val work_rxjava2: String = "androidx.work:work-rxjava2:" + Versions.androidx_work

    const val assent: String = "com.afollestad:assent:" + Versions.assent

    /**
     * https://github.com/andkulikov/transitions-everywhere
     */
    const val transitionseverywhere: String = "com.andkulikov:transitionseverywhere:" +
            Versions.transitionseverywhere

    /**
     * https://developer.android.com/studio
     */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * https://developer.android.com/studio
     */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/studio
     */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    const val crashlytics: String = "com.crashlytics.sdk.android:crashlytics:" +
            Versions.crashlytics

    const val com_diffplug_gradle_spotless_gradle_plugin: String =
            "com.diffplug.gradle.spotless:com.diffplug.gradle.spotless.gradle.plugin:" +
            Versions.com_diffplug_gradle_spotless_gradle_plugin

    /**
     * https://github.com/facebook/facebook-android-sdk
     */
    const val facebook_android_sdk: String = "com.facebook.android:facebook-android-sdk:" +
            Versions.facebook_android_sdk

    /**
     * https://github.com/facebook/stetho
     */
    const val stetho_js_rhino: String = "com.facebook.stetho:stetho-js-rhino:" +
            Versions.com_facebook_stetho

    /**
     * https://github.com/facebook/stetho
     */
    const val stetho_okhttp3: String = "com.facebook.stetho:stetho-okhttp3:" +
            Versions.com_facebook_stetho

    /**
     * https://github.com/facebook/stetho
     */
    const val stetho: String = "com.facebook.stetho:stetho:" + Versions.com_facebook_stetho

    const val frodo_api: String = "com.fernandocejas.frodo:frodo-api:" +
            Versions.com_fernandocejas_frodo

    const val frodo_plugin: String = "com.fernandocejas.frodo:frodo-plugin:" +
            Versions.com_fernandocejas_frodo

    const val frodo_runtime: String = "com.fernandocejas.frodo:frodo-runtime:" +
            Versions.com_fernandocejas_frodo

    /**
     * https://github.com/Commit451/Hyperion-Chuck
     */
    const val hyperion_chuck: String = "com.github.Commit451:Hyperion-Chuck:" +
            Versions.hyperion_chuck

    /**
     * https://github.com/ajitsing/Sherlock
     */
    const val sherlock_no_op: String = "com.github.ajitsing:sherlock-no-op:" +
            Versions.com_github_ajitsing

    /**
     * https://github.com/ajitsing/Sherlock
     */
    const val sherlock: String = "com.github.ajitsing:sherlock:" + Versions.com_github_ajitsing

    /**
     * https://github.com/aykuttasil/AndroidBasicHelper
     */
    const val androidbasichelper: String = "com.github.aykuttasil:AndroidBasicHelper:" +
            Versions.androidbasichelper

    /**
     * https://github.com/bumptech/glide
     */
    const val com_github_bumptech_glide_compiler: String = "com.github.bumptech.glide:compiler:" +
            Versions.com_github_bumptech_glide

    /**
     * https://github.com/bumptech/glide
     */
    const val glide: String = "com.github.bumptech.glide:glide:" +
            Versions.com_github_bumptech_glide

    /**
     * https://github.com/bumptech/glide
     */
    const val okhttp3_integration: String = "com.github.bumptech.glide:okhttp3-integration:" +
            Versions.com_github_bumptech_glide

    const val needs: String = "com.github.skydoves:needs:" + Versions.needs

    /**
     * https://github.com/vondear/RxTool
     */
    const val rxkit: String = "com.github.vondear.RxTool:RxKit:" + Versions.rxkit

    const val play_services_base: String = "com.google.android.gms:play-services-base:" +
            Versions.com_google_android_gms

    const val play_services_gcm: String = "com.google.android.gms:play-services-gcm:" +
            Versions.com_google_android_gms

    const val play_services_location: String = "com.google.android.gms:play-services-location:" +
            Versions.com_google_android_gms

    const val play_services_maps: String = "com.google.android.gms:play-services-maps:" +
            Versions.com_google_android_gms

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val material: String = "com.google.android.material:material:" + Versions.material

    /**
     * https://github.com/google/dagger
     */
    const val dagger_android_processor: String = "com.google.dagger:dagger-android-processor:" +
            Versions.com_google_dagger

    /**
     * https://github.com/google/dagger
     */
    const val dagger_android_support: String = "com.google.dagger:dagger-android-support:" +
            Versions.com_google_dagger

    /**
     * https://github.com/google/dagger
     */
    const val dagger_compiler: String = "com.google.dagger:dagger-compiler:" +
            Versions.com_google_dagger

    /**
     * https://github.com/google/dagger
     */
    const val dagger: String = "com.google.dagger:dagger:" + Versions.com_google_dagger

    const val firebase_auth: String = "com.google.firebase:firebase-auth:" + Versions.firebase_auth

    const val firebase_common_ktx: String = "com.google.firebase:firebase-common-ktx:" +
            Versions.firebase_common_ktx

    const val firebase_config: String = "com.google.firebase:firebase-config:" +
            Versions.firebase_config

    const val firebase_core: String = "com.google.firebase:firebase-core:" + Versions.firebase_core

    const val firebase_crash: String = "com.google.firebase:firebase-crash:" +
            Versions.firebase_crash

    const val firebase_database: String = "com.google.firebase:firebase-database:" +
            Versions.firebase_database

    const val firebase_dynamic_links: String = "com.google.firebase:firebase-dynamic-links:" +
            Versions.firebase_dynamic_links

    const val firebase_firestore_ktx: String = "com.google.firebase:firebase-firestore-ktx:" +
            Versions.firebase_firestore_ktx

    const val firebase_messaging: String = "com.google.firebase:firebase-messaging:" +
            Versions.firebase_messaging

    /**
     * http://tools.android.com/
     */
    const val google_services: String = "com.google.gms:google-services:" + Versions.google_services

    /**
     * https://github.com/googlemaps/android-maps-utils
     */
    const val android_maps_utils: String = "com.google.maps.android:android-maps-utils:" +
            Versions.android_maps_utils

    /**
     * https://github.com/JakeWharton/timber
     */
    const val timber: String = "com.jakewharton.timber:timber:" + Versions.timber

    /**
     * https://github.com/JakeWharton/butterknife/
     */
    const val butterknife_compiler: String = "com.jakewharton:butterknife-compiler:" +
            Versions.com_jakewharton

    /**
     * https://github.com/JakeWharton/butterknife/
     */
    const val butterknife: String = "com.jakewharton:butterknife:" + Versions.com_jakewharton

    /**
     * https://github.com/one-signal/OneSignal-Android-SDK
     */
    const val onesignal: String = "com.onesignal:OneSignal:" + Versions.onesignal

    /**
     * https://github.com/orhanobut/logger
     */
    const val logger: String = "com.orhanobut:logger:" + Versions.logger

    const val rxlocation: String = "com.patloew.rxlocation:rxlocation:" + Versions.rxlocation

    /**
     * https://github.com/jgilfelt/chuck
     */
    const val library_no_op: String = "com.readystatesoftware.chuck:library-no-op:" +
            Versions.com_readystatesoftware_chuck

    /**
     * https://github.com/jgilfelt/chuck
     */
    const val library: String = "com.readystatesoftware.chuck:library:" +
            Versions.com_readystatesoftware_chuck

    /**
     * http://github.com/square/leakcanary/
     */
    const val leakcanary_android: String = "com.squareup.leakcanary:leakcanary-android:" +
            Versions.leakcanary_android

    /**
     * https://github.com/square/okhttp
     */
    const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:" +
            Versions.logging_interceptor

    /**
     * https://github.com/square/picasso/
     */
    const val picasso: String = "com.squareup.picasso:picasso:" + Versions.picasso

    /**
     * https://github.com/square/retrofit/
     */
    const val adapter_rxjava2: String = "com.squareup.retrofit2:adapter-rxjava2:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit/
     */
    const val adapter_rxjava: String = "com.squareup.retrofit2:adapter-rxjava:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit/
     */
    const val converter_gson: String = "com.squareup.retrofit2:converter-gson:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit/
     */
    const val retrofit: String = "com.squareup.retrofit2:retrofit:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/tbruyelle/RxPermissions
     */
    const val rxpermissions: String = "com.tbruyelle.rxpermissions:rxpermissions:" +
            Versions.rxpermissions

    /**
     * https://github.com/willowtreeapps/Hyperion-Android
     */
    const val hyperion_attr: String = "com.willowtreeapps.hyperion:hyperion-attr:" +
            Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android
     */
    const val hyperion_build_config: String = "com.willowtreeapps.hyperion:hyperion-build-config:" +
            Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android
     */
    const val hyperion_core: String = "com.willowtreeapps.hyperion:hyperion-core:" +
            Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android
     */
    const val hyperion_crash: String = "com.willowtreeapps.hyperion:hyperion-crash:" +
            Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android
     */
    const val hyperion_disk: String = "com.willowtreeapps.hyperion:hyperion-disk:" +
            Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android
     */
    const val hyperion_geiger_counter: String =
            "com.willowtreeapps.hyperion:hyperion-geiger-counter:" +
            Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android
     */
    const val hyperion_measurement: String = "com.willowtreeapps.hyperion:hyperion-measurement:" +
            Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android
     */
    const val hyperion_phoenix: String = "com.willowtreeapps.hyperion:hyperion-phoenix:" +
            Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android
     */
    const val hyperion_recorder: String = "com.willowtreeapps.hyperion:hyperion-recorder:" +
            Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android
     */
    const val hyperion_shared_preferences: String =
            "com.willowtreeapps.hyperion:hyperion-shared-preferences:" +
            Versions.com_willowtreeapps_hyperion

    /**
     * https://github.com/willowtreeapps/Hyperion-Android
     */
    const val hyperion_timber: String = "com.willowtreeapps.hyperion:hyperion-timber:" +
            Versions.com_willowtreeapps_hyperion

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val onesignal_gradle_plugin: String =
            "gradle.plugin.com.onesignal:onesignal-gradle-plugin:" +
            Versions.onesignal_gradle_plugin

    const val io_fabric_tools_gradle: String = "io.fabric.tools:gradle:" +
            Versions.io_fabric_tools_gradle

    /**
     * https://github.com/ReactiveX/RxAndroid
     */
    const val rxandroid: String = "io.reactivex.rxjava2:rxandroid:" + Versions.rxandroid

    /**
     * https://github.com/ReactiveX/RxKotlin
     */
    const val rxkotlin: String = "io.reactivex.rxjava2:rxkotlin:" + Versions.rxkotlin

    /**
     * http://junit.org
     */
    const val junit: String = "junit:junit:" + Versions.junit

    const val org_ajoberstar_grgit_gradle_plugin: String =
            "org.ajoberstar.grgit:org.ajoberstar.grgit.gradle.plugin:" +
            Versions.org_ajoberstar_grgit_gradle_plugin

    /**
     * http://www.aspectj.org
     */
    const val aspectjrt: String = "org.aspectj:aspectjrt:" + Versions.aspectjrt

    /**
     * http://greenrobot.org/eventbus/
     */
    const val eventbus: String = "org.greenrobot:eventbus:" + Versions.eventbus

    /**
     * https://github.com/JetBrains/anko
     */
    const val anko: String = "org.jetbrains.anko:anko:" + Versions.anko

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:" + Versions.org_jetbrains_kotlinx

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:" +
            Versions.org_jetbrains_kotlinx

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_rx2: String = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2:" +
            Versions.org_jetbrains_kotlinx
}
